server:
  port: 0

spring:
  application:
    name: bank-rest-test

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  liquibase:
    enabled: false

  h2:
    console:
      enabled: true

security:
  jwt:
    access:
      key: testSecretKeytestSecretKeytestSecretKeytestSecretKey
      expiration-ms: 900000
  encryption:
    secret-key: dGVzdFNlY3JldEtleXRlc3RTZWNyZXRLZXl0ZXN0U2VjcmV0S2V5
    algorithm: AES
    transformation: AES/ECB/PKCS5Padding

logging:
  level:
    org.matvey.bankrest: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG