server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: bank-rest

  datasource:
    url: jdbc:postgresql://localhost:5432/bank_db
    username: postgres
    password: postgres

  liquibase:
    change-log: classpath:/db/migration/db.changelog-master.yml

security:
  jwt:
    access:
      key: 864cd532e9790537abbf50182f9681ff4db9c3a996fe9112d374ddc73b42854f
      expiration-ms: 900000

docs:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs